package com.hotelmanagement.hms.payment.service;
import com.hotelmanagement.hms.payment.dto.*; import com.hotelmanagement.hms.payment.model.*; import com.hotelmanagement.hms.payment.repository.*; import com.hotelmanagement.hms.folio.service.FolioService; import com.hotelmanagement.hms.folio.model.EntryKind; import com.hotelmanagement.hms.shared.service.OperationScope; import com.hotelmanagement.hms.shared.model.Money; import com.hotelmanagement.hms.shared.web.*; import com.hotelmanagement.hms.audit.service.AuditService; import static com.hotelmanagement.hms.identity.authorization.model.PermissionCode.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.*; import java.math.*; import java.util.*;
@Service @Transactional public class PaymentService {
 private final PaymentRepository payments;private final FolioService folios;private final OperationScope scope;private final AuditService audit;
 public PaymentService(PaymentRepository p,FolioService f,OperationScope s,AuditService a){payments=p;folios=f;scope=s;audit=a;}
 public PaymentResponse create(UUID hotel,UUID branch,PaymentRequest r){UUID actor=scope.branch(hotel,branch,PAYMENT_RECORD);var prior=payments.findByHotelIdAndBranchIdAndIdempotencyKey(hotel,branch,r.idempotencyKey());if(prior.isPresent()){var old=prior.get();if(!old.getFolioId().equals(r.folioId())||old.getOriginalAmount().compareTo(r.amount())!=0||old.getMethod()!=r.method()||!old.getCurrency().equals(r.currency())||old.getFxRate().compareTo(r.fxRate())!=0)throw new IllegalStateException("Payment key reused.");return PaymentResponse.from(old); } var locked=folios.lock(hotel,branch,r.folioId());if(!locked.getCurrency().equals(r.currency())||r.fxRate().compareTo(BigDecimal.ONE)!=0)throw new IllegalArgumentException("Use folio currency at rate 1.");if(r.method()==PaymentMethod.CREDIT)throw new IllegalArgumentException("Credit is not a payment method.");if(folios.balance(hotel,branch,r.folioId()).compareTo(r.amount())<0)throw new IllegalStateException("Payment exceeds balance.");var amount=Money.positive(r.amount());var fx=r.fxRate();var base=amount.multiply(fx).setScale(4,RoundingMode.HALF_UP);var p=payments.saveAndFlush(Payment.create(hotel,branch,r.folioId(),actor,r.method(),r.currency(),amount,fx,base,r.externalReference(),r.idempotencyKey(),actor));folios.post(hotel,branch,r.folioId(),base.negate(),EntryKind.PAYMENT,p.getId(),"Payment "+r.method(),actor);audit.record(hotel,branch,actor,"PAYMENT_POSTED","PAYMENT",p.getId());return PaymentResponse.from(p);}
 @Transactional(readOnly=true) public PaymentResponse get(UUID hotel,UUID branch,UUID id){scope.branch(hotel,branch,PAYMENT_VIEW);return PaymentResponse.from(payments.findByIdAndHotelIdAndBranchId(id,hotel,branch).orElseThrow(ApiException::notFound));}
 public void voidPayment(UUID hotel,UUID branch,UUID id){UUID actor=scope.branch(hotel,branch,PAYMENT_VOID);var p=payments.lock(id,hotel,branch).orElseThrow(ApiException::notFound);p.voidPayment();folios.post(hotel,branch,p.getFolioId(),p.getBaseAmount(),EntryKind.REFUND,p.getId(),"Payment void",actor);audit.record(hotel,branch,actor,"PAYMENT_VOIDED","PAYMENT",id);}
 public void refund(UUID hotel,UUID branch,UUID id){UUID actor=scope.branch(hotel,branch,PAYMENT_REFUND);var p=payments.lock(id,hotel,branch).orElseThrow(ApiException::notFound);p.refund();folios.post(hotel,branch,p.getFolioId(),p.getBaseAmount(),EntryKind.REFUND,p.getId(),"Payment refund",actor);audit.record(hotel,branch,actor,"PAYMENT_REFUNDED","PAYMENT",id);}
}


