# HMS production RabbitMQ configuration.
#
# RabbitMQ container hard memory limit: 320 MiB.
# Trigger RabbitMQ memory flow control before reaching
# the Docker container limit.

vm_memory_high_watermark.absolute = 200MiB