"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {all} from "@/lib/hms-api";
import {Panel,Empty,Field,inputStyle} from "@/components/operations/ui";
import {useLocale} from "@/components/LocaleProvider";
type Folio={id:string;customer_id:string;customer_name:string;currency:string;status:string;balance:number};
export default function Folios(){
 const {t}=useLocale();const [rows,setRows]=useState<Folio[]>([]);const [error,setError]=useState("");const [search,setSearch]=useState("");const [expanded,setExpanded]=useState<string|null>(null);
 useEffect(()=>{all<Folio>("folios").then(setRows).catch(e=>setError(e.message))},[]);
 const accounts=Object.values(rows.reduce<Record<string,{id:string;name:string;bills:Folio[]}>>((acc,r)=>{const key=r.customer_id;acc[key]??={id:key,name:r.customer_name,bills:[]};acc[key].bills.push(r);return acc},{}));
 return <Panel title="Guest Folios" error={error}><p className="text-slate-500">{t("One portfolio per customer, with all orders, stays and outstanding bills.")}</p><Field label="Search"><input className={inputStyle} value={search} onChange={e=>setSearch(e.target.value)}/></Field><div className="space-y-4">{accounts.filter(a=>a.name.toLowerCase().includes(search.toLowerCase())).map(a=>{const totals=a.bills.reduce<Record<string,number>>((s,b)=>{s[b.currency]=(s[b.currency]??0)+Number(b.balance);return s},{});return <section key={a.id} className="rounded-2xl border border-slate-200 bg-white shadow-sm overflow-hidden"><button type="button" className="w-full flex flex-wrap items-center justify-between gap-4 p-6 text-left hover:bg-slate-50" onClick={()=>setExpanded(expanded===a.id?null:a.id)} aria-expanded={expanded===a.id}><div><h2 className="font-semibold text-lg text-slate-900">{a.name}</h2><p className="text-sm text-slate-500">{t("Billing history")} · {a.bills.length}</p></div><div className="text-right"><p className="text-xs uppercase tracking-wide text-slate-500">{t("Balance")}</p>{Object.entries(totals).map(([currency,balance])=><p key={currency} className="text-lg font-semibold">{balance.toFixed(2)} {currency}</p>)}</div></button>{expanded===a.id&&<div className="overflow-auto border-t border-slate-100"><table className="w-full text-sm text-left"><thead className="bg-slate-50 text-slate-500"><tr>{["Status","Currency","Balance","Actions"].map(k=><th className="p-4" key={k}>{t(k)}</th>)}</tr></thead><tbody>{a.bills.map(b=><tr key={b.id} className="border-t border-slate-100"><td className="p-4">{t(b.status)}</td><td className="p-4">{b.currency}</td><td className="p-4">{Number(b.balance).toFixed(2)}</td><td className="p-4"><Link className="font-medium text-blue-700" href={`/folios/${b.id}`}>{t("Open customer folio")}</Link></td></tr>)}</tbody></table></div>}</section>})}{!accounts.length&&<Empty/>}</div></Panel>
}
