package com.hotelmanagement.hms.room.service;
import com.hotelmanagement.hms.room.dto.*;import com.hotelmanagement.hms.room.model.*;import com.hotelmanagement.hms.room.repository.*;
import com.hotelmanagement.hms.shared.service.OperationScope;import com.hotelmanagement.hms.shared.web.*;import com.hotelmanagement.hms.shared.model.Money;
import com.hotelmanagement.hms.audit.service.AuditService;import static com.hotelmanagement.hms.identity.authorization.model.PermissionCode.*;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.jdbc.core.JdbcTemplate;
import java.math.BigDecimal;import java.util.*;
@Service @Transactional
public class RoomService {
 private final RoomRepository rooms;private final RoomTypeRepository types;private final OperationScope scope;private final AuditService audit;private final JdbcTemplate db;
 public RoomService(RoomRepository rooms,RoomTypeRepository types,OperationScope scope,AuditService audit,JdbcTemplate db){this.rooms=rooms;this.types=types;this.scope=scope;this.audit=audit;this.db=db;}
 private void validateType(RoomTypeRequest r){if(r.standardOccupancy()<1||r.maxAdults()<1||r.maxChildren()<0||r.standardOccupancy()>r.maxAdults()+r.maxChildren())throw new IllegalArgumentException("Invalid occupancy.");Money.nonnegative(r.defaultRate());}
 private void updateType(RoomType type,RoomTypeRequest r){validateType(r);type.update(r.code().trim().toUpperCase(Locale.ROOT),r.name(),r.description(),r.standardOccupancy(),r.maxAdults(),r.maxChildren(),Money.nonnegative(r.defaultRate()),r.bedType(),r.bedDimensions());}
 public RoomTypeResponse type(UUID h,UUID b,RoomTypeRequest r){UUID actor=scope.branch(h,b,ROOM_MANAGE);scope.branch(h,b,ROOM_RATE_MANAGE);validateType(r);var type=RoomType.create(h,b,r.code(),r.name(),r.description(),r.standardOccupancy(),r.maxAdults(),r.maxChildren(),r.defaultRate());updateType(type,r);types.saveAndFlush(type);audit.record(h,b,actor,"ROOM_TYPE_CREATED","ROOM_TYPE",type.getId());return RoomTypeResponse.from(type);}
 public RoomTypeResponse editType(UUID h,UUID b,UUID id,RoomTypeRequest r){UUID actor=scope.branch(h,b,ROOM_MANAGE);scope.branch(h,b,ROOM_RATE_MANAGE);var type=types.lock(id,h,b).filter(RoomType::getActive).orElseThrow(ApiException::notFound);updateType(type,r);audit.record(h,b,actor,"ROOM_TYPE_UPDATED","ROOM_TYPE",id);return RoomTypeResponse.from(type);}
 public void deleteType(UUID h,UUID b,UUID id){UUID actor=scope.branch(h,b,ROOM_MANAGE);var type=types.lock(id,h,b).orElseThrow(ApiException::notFound);if(db.queryForObject("select count(*) from rooms where room_type_id=? and active",Integer.class,id)>0)throw new IllegalStateException("Remove or reassign rooms before deleting the room type.");type.archive();audit.record(h,b,actor,"ROOM_TYPE_ARCHIVED","ROOM_TYPE",id);}
 private void configure(UUID h,UUID b,Room room,RoomType type,RoomRequest r){
  boolean inherit=r.adults()==null||r.adults()==0;
  int adults=inherit?type.getMaxAdults():r.adults();int children=inherit?type.getMaxChildren():(r.children()==null?0:r.children());
  if(adults>type.getMaxAdults()||children>type.getMaxChildren()||adults<1||children<0)throw new IllegalArgumentException("Room exceeds type capacity.");
  var rate=r.nightlyRate()==null?type.getDefaultRate():Money.nonnegative(r.nightlyRate());
  if(rate.compareTo(type.getDefaultRate())!=0)scope.branch(h,b,ROOM_RATE_MANAGE);
  room.update(type.getId(),r.code().trim().toUpperCase(Locale.ROOT),r.floor(),r.beds(),r.bedType()==null?type.getBedType():r.bedType(),r.bedDimensions()==null?type.getBedDimensions():r.bedDimensions(),adults,children,rate);
 }
 public RoomResponse create(UUID h,UUID b,RoomRequest r){UUID actor=scope.branch(h,b,ROOM_MANAGE);var type=types.lock(r.roomTypeId(),h,b).filter(RoomType::getActive).orElseThrow(ApiException::notFound);var room=Room.create(h,b,type.getId(),r.code(),r.floor(),r.beds(),type.getBedType(),type.getBedDimensions(),type.getMaxAdults(),type.getMaxChildren(),true,HousekeepingState.CLEAN,RoomOperationalState.AVAILABLE);configure(h,b,room,type,r);rooms.saveAndFlush(room);audit.record(h,b,actor,"ROOM_CREATED","ROOM",room.getId());return response(room);}
 public RoomResponse edit(UUID h,UUID b,UUID id,RoomRequest r){UUID actor=scope.branch(h,b,ROOM_MANAGE);var type=types.lock(r.roomTypeId(),h,b).filter(RoomType::getActive).orElseThrow(ApiException::notFound);var room=rooms.lock(id,h,b).filter(Room::getActive).orElseThrow(ApiException::notFound);configure(h,b,room,type,r);if(db.queryForObject("select count(*) from reservation_rooms where room_id=? and active and (adults>? or children>?)",Integer.class,id,room.getAdults(),room.getChildren())>0)throw new IllegalStateException("Room capacity conflicts with an existing reservation.");audit.record(h,b,actor,"ROOM_UPDATED","ROOM",id);return response(room);}
 public void delete(UUID h,UUID b,UUID id){UUID actor=scope.branch(h,b,ROOM_MANAGE);var room=rooms.lock(id,h,b).orElseThrow(ApiException::notFound);if(db.queryForObject("select count(*) from reservation_rooms where room_id=? and active",Integer.class,id)>0)throw new IllegalStateException("Room has an active reservation.");room.activate(false);audit.record(h,b,actor,"ROOM_ARCHIVED","ROOM",id);}
 public RoomTypeResponse rate(UUID h,UUID b,UUID id,BigDecimal rate){UUID actor=scope.branch(h,b,ROOM_RATE_MANAGE);var type=types.lock(id,h,b).orElseThrow(ApiException::notFound);type.changeRate(rate);audit.record(h,b,actor,"ROOM_RATE_CHANGED","ROOM_TYPE",id);return RoomTypeResponse.from(type);}
 private RoomResponse response(Room room){var rate=room.getNightlyRate();if(rate==null)rate=types.findByIdAndHotelIdAndBranchId(room.getRoomTypeId(),room.getHotelId(),room.getBranchId()).orElseThrow(ApiException::notFound).getDefaultRate();return RoomResponse.from(room,rate);}
 @Transactional(readOnly=true) public PageResponse<RoomResponse> rooms(UUID h,UUID b,int page,int size){scope.branch(h,b,ROOM_VIEW);return PageResponse.from(rooms.findByHotelIdAndBranchId(h,b,scope.page(page,size)).map(this::response));}
 @Transactional(readOnly=true) public PageResponse<RoomTypeResponse> types(UUID h,UUID b,int page,int size){scope.branch(h,b,ROOM_VIEW);return PageResponse.from(types.findByHotelIdAndBranchId(h,b,scope.page(page,size)).map(RoomTypeResponse::from));}
 @Transactional(readOnly=true) public RoomResponse get(UUID h,UUID b,UUID id){scope.branch(h,b,ROOM_VIEW);return response(rooms.findByIdAndHotelIdAndBranchId(id,h,b).orElseThrow(ApiException::notFound));}
 public RoomResponse housekeeping(UUID h,UUID b,UUID id,HousekeepingState state){UUID actor=scope.branch(h,b,HOUSEKEEPING_UPDATE);var room=rooms.lock(id,h,b).orElseThrow(ApiException::notFound);room.housekeeping(state);audit.record(h,b,actor,"HOUSEKEEPING_"+state,"ROOM",id);return response(room);}
}
