"use client";
import {useLocale} from "@/components/LocaleProvider";
import {FormEvent,useEffect,useState} from "react";
import {useSession} from "next-auth/react";
import {api,all} from "@/lib/hms-api";
import {CurrencyField,HotelCurrency,PaymentAccount} from "./MoneyFields";
import {Field,inputStyle,buttonStyle} from "./ui";
export function FinanceSettings(){
 const {t}=useLocale();
 const {data:session}=useSession();const permissions=(session?.user as {permissions?:string[]})?.permissions??[];
 const [names,setNames]=useState<Record<string,string>>({});
 const [accounts,setAccounts]=useState<PaymentAccount[]>([]);const [currencies,setCurrencies]=useState<HotelCurrency[]>([]);
 const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 const [code,setCode]=useState("");const [currencyName,setCurrencyName]=useState("");
 const [name,setName]=useState("");const [method,setMethod]=useState("BANK_TRANSFER");const [currency,setCurrency]=useState("");const [kind,setKind]=useState("ACCOUNT_NUMBER");const [identifier,setIdentifier]=useState("");const [revision,setRevision]=useState(0);
 async function load(){const [a,c]=await Promise.all([all<PaymentAccount>("payment-accounts"),all<HotelCurrency>("currencies")]);setAccounts(a);setCurrencies(c);setRevision(r=>r+1);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function act(fn:()=>Promise<unknown>){setBusy(true);setError("");setMessage("");try{await fn();await load();setMessage("Saved");}catch(e){setError(e instanceof Error?e.message:"Unable to save.");}finally{setBusy(false);}}
 async function addAccount(e:FormEvent){e.preventDefault();await act(async()=>{await api("payment-accounts","POST",{name,method,currency,identifierType:kind,identifier:kind==="NONE"?null:identifier,active:true});setName("");setIdentifier("");});}
 return <section className="space-y-6 rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">{t("Currencies and payment accounts")}</h2>{error&&<p role="alert" className="text-red-700">{t(error)}</p>}{message&&<p role="status" className="text-emerald-700">{t(message)}</p>}
 <div className="space-y-3"><p>{t("Enable currencies for prices and transactions. Set their rates below as the value of one unit in the hotel accounting currency.")}</p>
 {currencies.map(c=><div key={c.code} className="flex justify-between gap-3"><span>{c.code} — {c.name} ({c.enabled?"active":"inactive"})</span>{permissions.includes("EXCHANGE_RATE_MANAGE")&&<button type="button" disabled={busy} onClick={()=>act(()=>api(`currencies/${c.code}`,"PUT",{...c,enabled:!c.enabled}))}>{t(c.enabled?"Deactivate":"Activate")}</button>}</div>)}
 {permissions.includes("EXCHANGE_RATE_MANAGE")&&<form className="flex flex-wrap gap-3 items-end" onSubmit={e=>{e.preventDefault();act(()=>api(`currencies/${code.toUpperCase()}`,"PUT",{name:currencyName,enabled:true}));}}><Field label="Currency code"><input className={inputStyle} required pattern="[A-Za-z]{3}" maxLength={3} placeholder="USD" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></Field><Field label="Currency name"><input className={inputStyle} required maxLength={100} value={currencyName} onChange={e=>setCurrencyName(e.target.value)}/></Field><button disabled={busy} className={buttonStyle}>{t("Add currency")}</button></form>}
 </div><div className="overflow-auto"><table className="w-full text-sm text-left"><thead><tr>{["Account","Type","Currency","Number / code","Status","Actions"].map(label=><th className="p-2" key={label}>{t(label)}</th>)}</tr></thead><tbody>{accounts.map(a=><tr key={a.id} className="border-t"><td className="p-2">{permissions.includes("HOTEL_SETTINGS_MANAGE")?<><input aria-label={t("Account name")} className={inputStyle} maxLength={100} value={names[a.id]??a.name} onChange={e=>setNames({...names,[a.id]:e.target.value})}/>{names[a.id]!==undefined&&names[a.id]!==a.name&&<button disabled={busy||!names[a.id].trim()} onClick={()=>act(()=>api(`payment-accounts/${a.id}`,"PUT",{name:names[a.id],active:a.active}))}>{t("Save name")}</button>}</>:a.name}</td><td>{a.method}</td><td>{a.currency}</td><td>{a.maskedIdentifier??"—"}</td><td>{t(a.active?"Active":"Inactive")}</td><td>{permissions.includes("HOTEL_SETTINGS_MANAGE")&&<button disabled={busy} onClick={()=>act(()=>api(`payment-accounts/${a.id}`,"PUT",{name:a.name,active:!a.active}))}>{t(a.active?"Deactivate":"Activate")}</button>}</td></tr>)}</tbody></table></div>
 {permissions.includes("HOTEL_SETTINGS_MANAGE")&&<form onSubmit={addAccount} className="grid gap-4 md:grid-cols-2"><Field label="Account name"><input className={inputStyle} required maxLength={100} placeholder="Bank of Kigali — USD" value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Payment type"><select className={inputStyle} value={method} onChange={e=>{setMethod(e.target.value);setKind(e.target.value==="BANK_TRANSFER"?"ACCOUNT_NUMBER":e.target.value==="MOBILE_MONEY"?"PHONE_NUMBER":"NONE");}}>{["BANK_TRANSFER","MOBILE_MONEY","CARD","CASH"].map(m=><option key={m}>{m}</option>)}</select></Field><CurrencyField key={revision} value={currency} onChange={setCurrency}/><Field label="Identifier type"><select className={inputStyle} value={kind} onChange={e=>setKind(e.target.value)}>{(method==="BANK_TRANSFER"?["ACCOUNT_NUMBER"]:method==="MOBILE_MONEY"?["PHONE_NUMBER","MERCHANT_CODE"]:["NONE","ACCOUNT_NUMBER"]).map(k=><option key={k}>{k}</option>)}</select></Field>{kind!=="NONE"&&<Field label="Number or merchant code"><input className={inputStyle} required maxLength={100} value={identifier} onChange={e=>setIdentifier(e.target.value)}/></Field>}<div><button className={buttonStyle} disabled={busy}>{t("Add payment account")}</button></div></form>}
 </section>;
}
