"use client";
import {useCallback,useEffect,useState} from "react";
import {useSession} from "next-auth/react";
import {api,all} from "@/lib/hms-api";
import {Panel,Field,inputStyle,buttonStyle,Empty} from "./ui";
import {useLocale} from "@/components/LocaleProvider";
export type Row=Record<string,unknown>&{id:string};
export type Input={key:string;label:string;type?:"number"|"checkbox"|"email"|"date"|"password";optional?:boolean;default?:unknown;options?:string[];lookup?:string;min?:number};
export function MasterData({title,resource,fields,columns,defaults={},extra}:{title:string;resource:string;fields:Input[];columns:string[];defaults?:Record<string,unknown>;extra?:(row:Row,refresh:()=>Promise<void>)=>React.ReactNode}){
 const {t}=useLocale();const {data:session}=useSession();const permissions=(session?.user as {permissions?:string[]})?.permissions;const permission=({customers:"CUSTOMER_MANAGE",vendors:"VENDOR_MANAGE",products:"PRODUCT_MANAGE",rooms:"ROOM_MANAGE","room-types":"ROOM_MANAGE",memberships:"USER_MANAGE",maintenance:"MAINTENANCE_MANAGE"} as Record<string,string>)[resource];const canCreate=permissions?.includes(permission)??false;const initial=()=>Object.fromEntries(fields.map(f=>[f.key,f.default??(f.type==="checkbox"?false:f.type==="number"?0:"")]));
 const [showCreate,setShowCreate]=useState(false);const [rows,setRows]=useState<Row[]>([]);const [values,setValues]=useState<Record<string,unknown>>(initial);const [choices,setChoices]=useState<Record<string,Row[]>>({});const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [selected,setSelected]=useState<Row|null>(null);const [search,setSearch]=useState("");
 const load=useCallback(()=>all<Row>(resource).then(setRows),[resource]);
 useEffect(()=>{load().catch(e=>setError(e.message));for(const f of fields)if(f.lookup)all<Row>(f.lookup).then(r=>setChoices(old=>({...old,[f.key]:r}))).catch(e=>setError(e.message))},[load,fields]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const body={...defaults,...values};for(const f of fields)if(f.optional&&body[f.key]==="")body[f.key]=null;await api(resource,"POST",body);setValues(initial());setShowCreate(false);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Panel title={title} error={error}>{canCreate&&<div className="flex justify-end"><button type="button" className={buttonStyle} onClick={()=>setShowCreate(!showCreate)}>{t(showCreate?"Cancel":"Create record")}</button></div>}{canCreate&&showCreate&&<form onSubmit={save} className="rounded-xl border bg-white p-5 space-y-4"><h2 className="font-semibold">{t("Create record")}</h2><div className="grid gap-4 md:grid-cols-3">{fields.map(f=><Field key={f.key} label={f.label}>{f.options||f.lookup?<select className={inputStyle} required={!f.optional} value={String(values[f.key]??"")} onChange={e=>setValues({...values,[f.key]:e.target.value})}><option value="">{t("Select")}</option>{f.options?.map(v=><option key={v} value={v}>{t(v)}</option>)}{choices[f.key]?.map(row=><option key={row.id} value={row.id}>{String(row.name??row.fullName??row.code??row.id)}</option>)}</select>:f.type==="checkbox"?<input type="checkbox" checked={Boolean(values[f.key])} onChange={e=>setValues({...values,[f.key]:e.target.checked})}/>:<input className={inputStyle} type={f.type??"text"} required={!f.optional} min={f.type==="number"?f.min??0:undefined} step={f.type==="number"?"0.0001":undefined} value={String(values[f.key]??"")} onChange={e=>setValues({...values,[f.key]:f.type==="number"?Number(e.target.value):e.target.value})}/>}</Field>)}</div><button className={buttonStyle} disabled={busy}>{t(busy?"Saving":"Save")}</button></form>}<Field label="Search"><input className={inputStyle} value={search} onChange={e=>setSearch(e.target.value)}/></Field><div className="rounded-xl border bg-white overflow-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{columns.map(key=><th className="p-3" key={key}>{t(fields.find(f=>f.key===key)?.label??key)}</th>)}{extra&&<th>{t("Actions")}</th>}</tr></thead><tbody>{rows.filter(r=>columns.some(k=>String(r[k]??"").toLowerCase().includes(search.toLowerCase()))).map(r=><tr key={r.id} className="border-t border-slate-100 hover:bg-slate-50/70">{columns.map(k=><td className="p-3" key={k}>{typeof r[k]==="boolean"?t(r[k]?"Yes":"No"):t(String(r[k]??""))}</td>)}{extra&&<td><button className="text-blue-700 underline" onClick={()=>setSelected(r)}>{t("Details")}</button></td>}</tr>)}</tbody></table>{!rows.length&&<Empty/>}</div>{selected&&extra?.(selected,load)}</Panel>
}



