"use client";
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {useSession} from "next-auth/react";
import {all,api} from "@/lib/hms-api";
import {buttonStyle} from "./ui";
import {useLocale} from "@/components/LocaleProvider";
type Order={id:string;customer_name:string;folio_id:string;status:string;total:number};type Item={id:string;product_name:string;quantity:number;unit_price:number;destination:string;preparation_status:string};
export function OrderHistory(){const {t}=useLocale();const {data:session}=useSession();const permissions=(session?.user as {permissions?:string[]})?.permissions??[];const [rows,setRows]=useState<Order[]>([]);const [items,setItems]=useState<Item[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const load=useCallback(()=>all<Order>("orders").then(setRows),[]);useEffect(()=>{load().catch(e=>setError(e.message));const timer=setInterval(()=>load().catch(e=>setError(e.message)),15000);return()=>clearInterval(timer)},[load]);async function act(id:string,action:string){setBusy(true);setError("");try{await api(`orders/${id}/${action}`,"POST",action==="status"?{status:"SERVED"}:undefined);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}return <section className="rounded-xl border bg-white p-5 space-y-4 overflow-auto"><h2 className="font-semibold">{t("Order history")}</h2>{error&&<p role="alert">{t(error)}</p>}<table className="w-full text-left text-sm"><thead><tr>{["Customer","Total","Status","Actions"].map(k=><th className="py-3" key={k}>{t(k)}</th>)}</tr></thead><tbody>{rows.map(r=><tr className="border-t" key={r.id}><td className="py-3">{r.customer_name}</td><td>{r.total}</td><td>{t(r.status)}</td><td className="flex flex-wrap gap-3 py-3"><button className="text-blue-700 underline" onClick={()=>api<{items:Item[]}>(`orders/${r.id}`).then(d=>setItems(d.items)).catch(e=>setError(e.message))}>{t("Details")}</button><Link className="text-blue-700 underline" href={`/folios/${r.folio_id}`}>{t("Folio")}</Link>{r.status==="READY"&&permissions.includes("ORDER_SEND")&&<button className={buttonStyle} disabled={busy} onClick={()=>act(r.id,"status")}>{t("Mark served")}</button>}{r.status!=="VOIDED"&&permissions.includes("ORDER_VOID")&&<button className="text-red-700" disabled={busy} onClick={()=>act(r.id,"void")}>{t("Void order")}</button>}</td></tr>)}</tbody></table>{items.length>0&&<div className="rounded border p-4">{items.map(i=><p key={i.id}>{i.quantity} × {i.product_name} · {i.unit_price} · {t(i.destination)} · {t(i.preparation_status)}</p>)}</div>}</section>}
