"use client";
import {useEffect,useState} from "react";
import {useSession} from "next-auth/react";
import {all,api} from "@/lib/hms-api";
import {Field,inputStyle,buttonStyle} from "./ui";
import {useLocale} from "@/components/LocaleProvider";
type Shift={id:string;cashier_user_id:string;cashier_name:string;status:string;opening_float:number;expected_amount:number;counted_amount:number;difference:number};
export function Shifts(){const {t}=useLocale();const {data:session}=useSession();const [rows,setRows]=useState<Shift[]>([]);const [amount,setAmount]=useState(0);const [counted,setCounted]=useState(0);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const role=(session?.user as {role?:string})?.role;const own=rows.find(r=>r.cashier_user_id===session?.user?.id&&r.status==="OPEN");const canOpen=(session?.user as {permissions?:string[]})?.permissions?.includes("CASHIER_SHIFT_OPEN")??false;async function load(){setRows(await all<Shift>("cashier-shifts"))}useEffect(()=>{load().catch(e=>setError(e.message))},[]);async function act(fn:()=>Promise<unknown>){setBusy(true);setError("");try{await fn();await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}return <section className="rounded-2xl border bg-white p-6 space-y-4"><h2 className="font-semibold">{t("Cashier shifts")}</h2>{error&&<p role="alert">{t(error)}</p>}{canOpen&&!own&&<div className="flex items-end gap-3"><Field label="Opening float"><input type="number" min="0" className={inputStyle} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></Field><button className={buttonStyle} disabled={busy||amount<0} onClick={()=>act(()=>api("cashier-shifts","POST",{openingFloat:amount}))}>{t("Open shift")}</button></div>}{own&&<div className="flex items-end gap-3"><Field label="Counted cash"><input type="number" min="0" className={inputStyle} value={counted} onChange={e=>setCounted(Number(e.target.value))}/></Field><button className={buttonStyle} disabled={busy||counted<0} onClick={()=>act(()=>api(`cashier-shifts/${own.id}/close?counted=${counted}`,"POST"))}>{t("Close shift")}</button></div>}<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Cashier","Status","Opening float","Expected cash","Counted cash","Difference","Actions"].map(s=><th className="py-2" key={s}>{t(s)}</th>)}</tr></thead><tbody>{rows.map(r=><tr className="border-t" key={r.id}><td className="py-2">{r.cashier_name}</td><td>{t(r.status)}</td><td>{r.opening_float}</td><td>{r.expected_amount}</td><td>{r.counted_amount}</td><td>{r.difference}</td><td>{r.status==="CLOSED"&&["OWNER","MANAGER","ACCOUNTANT","SUPERVISOR"].includes(role??"")&&<button className={buttonStyle} disabled={busy} onClick={()=>act(()=>api(`cashier-shifts/${r.id}/reconcile`,"POST"))}>{t("Reconcile")}</button>}</td></tr>)}</tbody></table></div></section>}

