package com.hotelmanagement.hms.housekeeping.service;
import com.hotelmanagement.hms.housekeeping.dto.*;import com.hotelmanagement.hms.housekeeping.model.*;import com.hotelmanagement.hms.housekeeping.repository.*;
import com.hotelmanagement.hms.shared.service.OperationScope;import com.hotelmanagement.hms.shared.web.*;import com.hotelmanagement.hms.audit.service.AuditService;
import com.hotelmanagement.hms.room.repository.RoomRepository;import com.hotelmanagement.hms.room.model.HousekeepingState;
import static com.hotelmanagement.hms.identity.authorization.model.PermissionCode.*;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.*;import org.springframework.jdbc.core.JdbcTemplate;import java.util.*;
@Service @Transactional
public class HousekeepingTaskService {
 private final HousekeepingTaskRepository repo;private final OperationScope scope;private final AuditService audit;private final JdbcTemplate db;private final RoomRepository rooms;
 public HousekeepingTaskService(HousekeepingTaskRepository r,OperationScope s,AuditService a,JdbcTemplate d,RoomRepository rooms){repo=r;scope=s;audit=a;db=d;this.rooms=rooms;}
 private void assignee(UUID h,UUID b,UUID user){if(user!=null&&!Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from hotel_memberships m join users u on u.id=m.user_id join membership_roles mr on mr.membership_id=m.id join roles r on r.id=mr.role_id join role_permissions rp on rp.role_id=r.id join permissions p on p.id=rp.permission_id where m.hotel_id=? and m.user_id=? and m.status='ACTIVE' and u.status='ACTIVE' and r.active and p.code='HOUSEKEEPING_UPDATE' and (m.all_branches or exists(select 1 from membership_branch_access ba where ba.membership_id=m.id and ba.branch_id=?)))",Boolean.class,h,user,b)))throw new IllegalArgumentException("Assignee must be active housekeeping staff in this branch.");}
 public UUID create(UUID h,UUID b,HousekeepingTaskRequest q){UUID actor=scope.branch(h,b,HOUSEKEEPING_UPDATE);rooms.findByIdAndHotelIdAndBranchId(q.roomId(),h,b).orElseThrow(ApiException::notFound);assignee(h,b,q.assignedUserId());var task=repo.save(HousekeepingTask.create(h,b,q.roomId(),q.assignedUserId(),q.taskDate(),q.notes()));audit.record(h,b,actor,"HOUSEKEEPING_TASK_CREATED","HOUSEKEEPING_TASK",task.getId());return task.getId();}
 public void assign(UUID h,UUID b,UUID id,UUID user){UUID actor=scope.branch(h,b,HOUSEKEEPING_UPDATE);assignee(h,b,user);var task=lock(h,b,id);if(Set.of("DONE","CANCELLED").contains(task.get("status")))throw new IllegalStateException("Task is closed.");db.update("update housekeeping_tasks set assigned_user_id=? where id=?",user,id);audit.record(h,b,actor,"HOUSEKEEPING_ASSIGNED","HOUSEKEEPING_TASK",id);}
 private Map<String,Object> lock(UUID h,UUID b,UUID id){var rows=db.queryForList("select * from housekeeping_tasks where id=? and hotel_id=? and branch_id=? for update",id,h,b);if(rows.isEmpty())throw ApiException.notFound();return rows.getFirst();}
 public void update(UUID h,UUID b,UUID id,HousekeepingTaskStatus next){UUID actor=scope.branch(h,b,HOUSEKEEPING_UPDATE);var task=lock(h,b,id);String current=(String)task.get("status");if(next==null||!(current.equals("OPEN")&&next==HousekeepingTaskStatus.IN_PROGRESS||current.equals("IN_PROGRESS")&&next==HousekeepingTaskStatus.DONE||!Set.of("DONE","CANCELLED").contains(current)&&next==HousekeepingTaskStatus.CANCELLED))throw new IllegalStateException("Invalid task transition.");if(next==HousekeepingTaskStatus.DONE)rooms.lock((UUID)task.get("room_id"),h,b).orElseThrow(ApiException::notFound).housekeeping(HousekeepingState.CLEAN);db.update("update housekeeping_tasks set status=? where id=?",next.name(),id);audit.record(h,b,actor,"HOUSEKEEPING_TASK_"+next,"HOUSEKEEPING_TASK",id);}
 @Transactional(readOnly=true) public List<Map<String,Object>> list(UUID h,UUID b){scope.branch(h,b,HOUSEKEEPING_VIEW);return db.queryForList("select t.*,r.code room_code,u.full_name assigned_name from housekeeping_tasks t join rooms r on r.id=t.room_id left join users u on u.id=t.assigned_user_id where t.hotel_id=? and t.branch_id=? order by t.task_date desc,t.id limit 100",h,b);}
 @Transactional(readOnly=true) public List<Map<String,Object>> staff(UUID h,UUID b){scope.branch(h,b,HOUSEKEEPING_VIEW);return db.queryForList("select distinct u.id,u.full_name name from users u join hotel_memberships m on m.user_id=u.id join membership_roles mr on mr.membership_id=m.id join roles r on r.id=mr.role_id join role_permissions rp on rp.role_id=r.id join permissions p on p.id=rp.permission_id where m.hotel_id=? and m.status='ACTIVE' and u.status='ACTIVE' and r.active and p.code='HOUSEKEEPING_UPDATE' and (m.all_branches or exists(select 1 from membership_branch_access ba where ba.membership_id=m.id and ba.branch_id=?)) order by name",h,b);}
}
