"use client";
import {useCallback,useEffect,useState} from "react";
import {api,all} from "@/lib/hms-api";
import {useLocale} from "@/components/LocaleProvider";
import {Panel,Field,inputStyle,buttonStyle,Empty} from "@/components/operations/ui";
type Vendor={id:string;name:string};type Product={id:string;name:string;purchasePrice:number;purchasable:boolean;active:boolean};type Purchase={id:string;reference:string;vendor_name:string;status:string;total:number;paid:number};
export default function Purchasing(){const {t}=useLocale();const [rows,setRows]=useState<Purchase[]>([]);const [vendors,setVendors]=useState<Vendor[]>([]);const [products,setProducts]=useState<Product[]>([]);const [vendor,setVendor]=useState("");const [reference,setReference]=useState("");const [product,setProduct]=useState("");const [quantity,setQuantity]=useState(1);const [price,setPrice]=useState(0);const [lines,setLines]=useState<{productId:string;name:string;quantity:number;unitPrice:number}[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [selected,setSelected]=useState<Purchase|null>(null);const [amount,setAmount]=useState(0);const [method,setMethod]=useState("CASH");
 const load=useCallback(()=>all<Purchase>("purchase-orders").then(setRows),[]);
 useEffect(()=>{Promise.all([load(),all<Vendor>("vendors").then(setVendors),all<Product>("products").then(p=>setProducts(p.filter(x=>x.purchasable&&x.active)))]).catch(e=>setError(e.message))},[load]);
 async function act(fn:()=>Promise<unknown>){setBusy(true);setError("");try{await fn();await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Panel title="Purchasing" error={error}><div className="rounded-xl border bg-white p-5 space-y-4"><div className="grid gap-4 md:grid-cols-2"><Field label="Vendor"><select className={inputStyle} value={vendor} onChange={e=>setVendor(e.target.value)}><option value="">{t("Select vendor")}</option>{vendors.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></Field><Field label="Reference"><input className={inputStyle} value={reference} onChange={e=>setReference(e.target.value)}/></Field></div><div className="grid gap-4 md:grid-cols-4"><Field label="Product"><select className={inputStyle} value={product} onChange={e=>{setProduct(e.target.value);setPrice(Number(products.find(p=>p.id===e.target.value)?.purchasePrice??0))}}><option value="">{t("Select product")}</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Quantity"><input className={inputStyle} type="number" min="0.0001" step="0.0001" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></Field><Field label="Purchase unit price"><input className={inputStyle} type="number" min="0" step="0.0001" value={price} onChange={e=>setPrice(Number(e.target.value))}/></Field><button className={buttonStyle} disabled={!product||quantity<=0||price<0||lines.some(l=>l.productId===product)} onClick={()=>setLines([{productId:product,name:products.find(p=>p.id===product)!.name,quantity,unitPrice:price},...lines])}>{t("Add item")}</button></div>{lines.map(l=><p key={l.productId} className="flex justify-between">{l.quantity} × {l.name} <span>{(l.quantity*l.unitPrice).toFixed(2)} <button onClick={()=>setLines(lines.filter(x=>x!==l))}>{t("Remove")}</button></span></p>)}<p className="font-semibold">{t("Grand total")}: {lines.reduce((s,l)=>s+l.quantity*l.unitPrice,0).toFixed(2)}</p><button className={buttonStyle} disabled={busy||!vendor||!reference.trim()||!lines.length} onClick={()=>act(async()=>{await api("purchase-orders","POST",{vendorId:vendor,reference,items:lines.map(({productId,quantity,unitPrice})=>({productId,quantity,unitPrice}))});setLines([]);setReference("")})}>{t("Create purchase")}</button></div>
 <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead><tr>{["Reference","Vendor","Status","Total","Paid","Balance","Actions"].map(s=><th className="p-3" key={s}>{t(s)}</th>)}</tr></thead><tbody>{rows.map(r=><tr className="border-t" key={r.id}><td className="p-3">{r.reference}</td><td>{r.vendor_name}</td><td>{t(r.status)}</td><td>{r.total}</td><td>{r.paid}</td><td>{(Number(r.total)-Number(r.paid)).toFixed(2)}</td><td className="flex gap-2 p-3">{r.status==="DRAFT"&&<button className={buttonStyle} disabled={busy} onClick={()=>act(()=>api(`purchase-orders/${r.id}/approve`,"POST"))}>{t("Approve")}</button>}{r.status==="APPROVED"&&<button className={buttonStyle} disabled={busy} onClick={()=>act(()=>api(`purchase-orders/${r.id}/receive`,"POST"))}>{t("Receive goods")}</button>}{["APPROVED","RECEIVED"].includes(r.status)&&Number(r.total)>Number(r.paid)&&<button className={buttonStyle} onClick={()=>{setSelected(r);setAmount(Number(r.total)-Number(r.paid))}}>{t("Pay vendor")}</button>}</td></tr>)}</tbody></table>{!rows.length&&<Empty/>}</div>
 {selected&&<div className="rounded-xl border bg-white p-5 space-y-4"><h2>{t("Pay vendor")}: {selected.reference}</h2><Field label="Amount"><input className={inputStyle} type="number" min="0.0001" max={Number(selected.total)-Number(selected.paid)} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></Field><Field label="Payment method"><select className={inputStyle} value={method} onChange={e=>setMethod(e.target.value)}>{["CASH","MOBILE_MONEY","CARD","BANK_TRANSFER"].map(m=><option key={m} value={m}>{t(m)}</option>)}</select></Field><button className={buttonStyle} disabled={busy||amount<=0} onClick={()=>act(async()=>{await api(`purchase-orders/${selected.id}/payments`,"POST",{amount,method,requestId:crypto.randomUUID()});setSelected(null)})}>{t("Confirm payment")}</button></div>}
 </Panel>}
