"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {api,all} from "@/lib/hms-api";
import {Panel,Field,inputStyle,buttonStyle} from "@/components/operations/ui";
import {useLocale} from "@/components/LocaleProvider";
type Room={id:string;code:string;roomTypeId:string;adults:number;children:number;bedType:string;bedDimensions:string};type Customer={id:string;name:string;kind:string;active:boolean};
export default function NewReservation(){const {t}=useLocale();const [checkIn,setIn]=useState("");const [checkOut,setOut]=useState("");const [rooms,setRooms]=useState<Room[]>([]);const [customers,setCustomers]=useState<Customer[]>([]);const [customer,setCustomer]=useState("");const [selected,setSelected]=useState<Record<string,{adults:number;children:number}>>({});const [notes,setNotes]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [preview,setPreview]=useState(false);const [result,setResult]=useState<{reference:string;folioId:string}|null>(null);const [checked,setChecked]=useState("");
 useEffect(()=>{const q=new URLSearchParams(window.location.search);setIn(q.get("checkIn")??"");setOut(q.get("checkOut")??"");all<Customer>("customers").then(c=>setCustomers(c.filter(x=>x.active))).catch(e=>setError(e.message))},[]);
 function dates(a:string,b:string){setIn(a);setOut(b);setRooms([]);setSelected({});setPreview(false);setChecked("");setResult(null)}
 async function availability(){setBusy(true);setError("");try{const list=await all<Room>(`reservations/availability?checkIn=${checkIn}&checkOut=${checkOut}&adults=1&children=0`);setRooms(list);setSelected({});setChecked(`${checkIn}/${checkOut}`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function reserve(){setBusy(true);setError("");try{setResult(await api("reservations","POST",{bookingCustomerId:customer,checkIn,checkOut,adults:Object.values(selected).reduce((n,r)=>n+r.adults,0),children:Object.values(selected).reduce((n,r)=>n+r.children,0),rooms:Object.entries(selected).map(([roomId,counts])=>({roomId,...counts,guestIds:[]})),notes}));setSelected({});setRooms([]);setChecked("");setPreview(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Panel title="New reservation" error={error}><div className="rounded-xl border bg-white p-5 space-y-4"><h2 className="font-semibold">{t("Choose dates first")}</h2><div className="grid gap-4 md:grid-cols-3"><Field label="Check-in date"><input className={inputStyle} type="date" value={checkIn} disabled={busy} onChange={e=>dates(e.target.value,checkOut)}/></Field><Field label="Check-out date"><input className={inputStyle} type="date" min={checkIn} value={checkOut} disabled={busy} onChange={e=>dates(checkIn,e.target.value)}/></Field><button className={buttonStyle} disabled={busy||!checkIn||checkOut<=checkIn} onClick={availability}>{t("Check availability")}</button></div></div>
 {checked===`${checkIn}/${checkOut}`&&<><div className="rounded-xl border bg-white p-5 space-y-4"><Field label="Person or company"><select className={inputStyle} value={customer} onChange={e=>{setCustomer(e.target.value);setPreview(false)}}><option value="">{t("Select customer")}</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} · {t(c.kind)}</option>)}</select></Field><Link href="/customers" className="text-blue-700 underline">{t("Create customer or company")}</Link></div><div className="grid gap-4 md:grid-cols-3">{rooms.map(r=><article className={`rounded-xl border p-5 space-y-3 ${selected[r.id]?"border-blue-500 bg-blue-50":"bg-white"}`} key={r.id}><label className="flex gap-3 font-semibold"><input type="checkbox" checked={!!selected[r.id]} onChange={e=>{const next={...selected};if(e.target.checked)next[r.id]={adults:1,children:0};else delete next[r.id];setSelected(next);setPreview(false)}}/>{t("Room")} {r.code}</label><p>{r.bedType} · {r.bedDimensions}</p><p>{t("Capacity")}: {r.adults} {t("Adults")}, {r.children} {t("Children")}</p>{selected[r.id]&&<div className="grid grid-cols-2 gap-3">{(["adults","children"] as const).map(k=><Field label={k==="adults"?"Adults":"Children"} key={k}><input className={inputStyle} type="number" min={k==="adults"?1:0} max={r[k]} value={selected[r.id][k]} onChange={e=>{setSelected({...selected,[r.id]:{...selected[r.id],[k]:Number(e.target.value)}});setPreview(false)}}/></Field>)}</div>}</article>)}</div>{!rooms.length&&<p>{t("No rooms available for these dates")}</p>}<Field label="Notes"><textarea className={inputStyle} value={notes} onChange={e=>setNotes(e.target.value)}/></Field><button className={buttonStyle} disabled={!customer||!Object.keys(selected).length||Object.entries(selected).some(([id,x])=>{const r=rooms.find(r=>r.id===id)!;return x.adults<1||x.adults>r.adults||x.children<0||x.children>r.children||!Number.isInteger(x.adults)||!Number.isInteger(x.children)})} onClick={()=>setPreview(true)}>{t("Preview reservation")}</button></>}
 {preview&&<div className="rounded-xl border border-blue-300 bg-blue-50 p-5 space-y-3"><h2>{customers.find(c=>c.id===customer)?.name}</h2><p>{checkIn} → {checkOut}</p>{Object.entries(selected).map(([id,c])=><p key={id}>{t("Room")} {rooms.find(r=>r.id===id)?.code}: {c.adults} {t("Adults")}, {c.children} {t("Children")}</p>)}<button className={buttonStyle} disabled={busy} onClick={reserve}>{t("Confirm reservation")}</button></div>}
 {result&&<p role="status">{t("Reservation confirmed")}: {result.reference} · <Link className="text-blue-700 underline" href={`/folios/${result.folioId}`}>{t("Open customer folio")}</Link></p>}</Panel>
}
