"use client";
import {useCallback,useEffect,useState} from "react";
import {useSession} from "next-auth/react";
import {MasterData,Input,Row} from "@/components/operations/MasterData";
import {buttonStyle} from "@/components/operations/ui";
import {all,api} from "@/lib/hms-api";
import {useLocale} from "@/components/LocaleProvider";
const fields:Input[]=[{key:"fullName",label:"Full name"},{key:"email",label:"Email",type:"email"},{key:"password",label:"Initial password",type:"password"},{key:"phone",label:"Phone",optional:true},{key:"preferredLanguage",label:"Language",options:["en","fr","rw"],default:"en"},{key:"allBranches",label:"All branches",type:"checkbox",default:true}];
function Assignment({member}:{member:Row}){const {t}=useLocale();const {data:session}=useSession();const permissions=(session?.user as {permissions?:string[]})?.permissions??[];const [roles,setRoles]=useState<{id:string;code:string}[]>([]);const [assigned,setAssigned]=useState<string[]>([]);const [status,setStatus]=useState(String(member.status));const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const load=useCallback(async()=>{const [catalog,current]=await Promise.all([all<{id:string;code:string}>("roles"),all<{id:string}>(`memberships/${member.id}/roles`)]);setRoles(catalog);setAssigned(current.map(r=>r.id))},[member.id]);useEffect(()=>{load().catch(e=>setError(e.message))},[load]);async function toggle(id:string,checked:boolean){setBusy(true);setError("");try{await api(`memberships/${member.id}/roles/${id}`,checked?"PUT":"DELETE");await load();setMessage("Roles updated")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}async function toggleStatus(){setBusy(true);setError("");try{const next=status==="ACTIVE"?"SUSPENDED":"ACTIVE";await api(`memberships/${member.id}/status`,"PUT",{status:next});setStatus(next);setMessage("Saved")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><header className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-semibold">{String(member.fullName??member.email)}</h2><p className="mt-1 text-sm text-slate-500">{String(member.email)}</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-medium text-blue-700">{t(status)}</span></header><p className="my-5 text-sm text-slate-500">{t("Select all roles this account needs. Permissions are combined.")}</p>{error&&<p role="alert" className="mb-4 rounded-lg bg-red-50 p-3 text-red-700">{t(error)}</p>}<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{roles.map(role=><label key={role.id} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-4 text-sm ${assigned.includes(role.id)?"border-blue-200 bg-blue-50 text-blue-800":"border-slate-200 text-slate-600"}`}><input type="checkbox" checked={assigned.includes(role.id)} disabled={busy||!permissions.includes("ROLE_MANAGE")} onChange={e=>toggle(role.id,e.target.checked)}/>{t(role.code)}</label>)}</div><footer className="mt-5 flex items-center justify-between border-t pt-5">{permissions.includes("USER_MANAGE")&&<button className={buttonStyle} disabled={busy} onClick={toggleStatus}>{t(status==="ACTIVE"?"Suspend account":"Activate account")}</button>}{message&&<p role="status" className="text-sm text-emerald-700">{t(message)}</p>}</footer></section>}
export default function Staff(){return <MasterData title="Staff" resource="memberships" fields={fields} columns={["fullName","email","status","allBranches"]} extra={row=><Assignment key={row.id} member={row}/>}/>}
