"use client";
import {useEffect,useState} from 'react';
import {useLocale} from "@/components/LocaleProvider";
import {signOut} from 'next-auth/react';
export default function PlatformPanel(){ const {t,locale,setLocale}=useLocale();
 const [hotels,setHotels]=useState<any[]>([]),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/platform/hotels');const d=await r.json();if(!r.ok)throw Error(d.message??'Unable to load hotels');setHotels(d);}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){
  e.preventDefault();const form=e.currentTarget;const data=new FormData(form);setBusy(true);setError('');setSuccess('');
  const value=(key:string)=>String(data.get(key)??'');
  try{const r=await fetch('/api/platform/hotels',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:value('email'),password:value('password'),fullName:value('fullName'),preferredLanguage:value('language'),hotel:{code:value('code').toUpperCase(),legalName:value('hotelName'),displayName:value('hotelName'),currencyCode:'RWF',timezone:'Africa/Kigali',defaultLanguage:value('language')}})});const d=await r.json();if(!r.ok)throw Error(d.message??'Unable to create hotel');setSuccess('Hotel, owner account, trial and main branch created. The owner can now sign in with the email and password you entered.');form.reset();await load();}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}
 }
 return <main className="min-h-screen bg-slate-50 text-slate-900 p-6 md:p-12"><div className="max-w-5xl mx-auto"><select aria-label={t("Language")} value={locale} onChange={e=>setLocale(e.target.value as "en"|"fr"|"rw")} className="mb-4 border rounded p-2"><option value="en">English</option><option value="fr">Français</option><option value="rw">Kinyarwanda</option></select><header className="flex justify-between items-center mb-8"><div><p className="text-blue-700 font-semibold">HotelPro · {t("Platform administration")}</p><h1 className="text-3xl font-bold mt-2">{t("Hotels and owners")}</h1></div><button onClick={()=>signOut({callbackUrl:'/login'})} className="border rounded-lg px-4 py-2">{t("Sign out")}</button></header>
 {error&&<p role="alert" className="bg-red-100 text-red-800 p-4 rounded-lg mb-4">{t(error)}</p>}{success&&<p role="status" className="bg-green-100 text-green-800 p-4 rounded-lg mb-4">{t(success)}</p>}
 <section className="bg-white border rounded-2xl p-6 mb-8"><h2 className="text-xl font-semibold mb-4">{t("Create a hotel and owner account")}</h2><form onSubmit={submit} className="grid md:grid-cols-2 gap-4">{[['hotelName','Hotel name','text'],['code','Unique hotel code','text'],['fullName','Owner full name','text'],['email','Owner email','email'],['password','Initial password (at least 12 characters)','password']].map(([name,label,type])=><label key={name} className="text-sm font-medium">{t(label)}<input name={name} type={type} minLength={name==='password'?12:1} required autoComplete={name==='password'?'new-password':'off'} className="block w-full border border-slate-300 rounded-lg p-3 mt-1"/></label>)}<label className="text-sm font-medium">{t("Language")}<select name="language" className="block w-full border rounded-lg p-3 mt-1"><option value="en">English</option><option value="fr">Français</option><option value="rw">Kinyarwanda</option></select></label><button disabled={busy} className="bg-blue-600 text-white p-3 rounded-lg disabled:opacity-50">{t(busy?'Creating…':'Create hotel and owner')}</button></form></section>
 <section className="bg-white border rounded-2xl p-6"><h2 className="text-xl font-semibold mb-4">{t("Registered hotels")}</h2>{hotels.length===0?<p>{t("No hotels registered.")}</p>:<table className="w-full text-left"><thead><tr><th className="p-3">{t("Hotel")}</th><th>{t("Code")}</th><th>{t("Status")}</th></tr></thead><tbody>{hotels.map(h=><tr key={h.id} className="border-t"><td className="p-3">{h.name}</td><td>{h.code}</td><td>{t(h.status)}</td></tr>)}</tbody></table>}</section></div></main>
}

