"use client";
import {use,useCallback,useEffect,useRef,useState} from "react";
import {api,all} from "@/lib/hms-api";
import {Panel,Field,inputStyle,buttonStyle} from "@/components/operations/ui";
import {useLocale} from "@/components/LocaleProvider";
type Folio={id:string;customerId:string;currency:string;status:string;balance:number};type Entry={id:string;kind:string;amount:number;memo:string};
export default function FolioDetail({params}:{params:Promise<{id:string}>}){const {id}=use(params);const {t}=useLocale();const [folio,setFolio]=useState<Folio|null>(null);const [entries,setEntries]=useState<Entry[]>([]);const [customer,setCustomer]=useState("");const [parts,setParts]=useState([{method:"CASH",amount:0}]);const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const key=useRef("");const [collectionScope,setCollectionScope]=useState("FOOD");
 const load=useCallback(async()=>{const f=await api<Folio>(`folios/${id}`);setFolio(f);setEntries(await all<Entry>(`folios/${id}/entries`));const c=await api<{name:string}>(`customers/${f.customerId}`);setCustomer(c.name)},[id]);useEffect(()=>{load().catch(e=>setError(e.message))},[load]);
 const total=parts.reduce((s,p)=>s+Number(p.amount),0);
 async function submit(){setBusy(true);setError("");try{key.current||=crypto.randomUUID();await api("payment-approvals","POST",{folioId:id,requestId:key.current,parts,collectionScope});setMessage("Payment pending approval");setParts([{method:"CASH",amount:0}]);key.current="";await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Panel title="Guest Folios" error={error}>{folio&&<><div className="rounded-xl border bg-white p-5 space-y-2"><h2 className="text-xl font-semibold">{customer}</h2><p>{t(folio.status)}</p><p className="text-2xl">{t("Balance")}: {folio.balance} {folio.currency}</p><table className="w-full text-left text-sm"><thead><tr>{["Type","Description","Amount"].map(x=><th className="py-3" key={x}>{t(x)}</th>)}</tr></thead><tbody>{entries.map(e=><tr className="border-t" key={e.id}><td className="py-3">{t(e.kind)}</td><td>{e.memo}</td><td>{e.amount}</td></tr>)}</tbody></table></div>
 {folio.status!=="CLOSED"&&Number(folio.balance)>0&&<div className="rounded-xl border bg-white p-5 space-y-4"><h2 className="font-semibold">{t("Split payment")}</h2><Field label="Payment covers"><select className={inputStyle} value={collectionScope} onChange={e=>{key.current="";setCollectionScope(e.target.value)}}><option value="FOOD">{t("Food and services")}</option><option value="ROOM">{t("Room charges")}</option></select></Field>{parts.map((p,index)=><div className="grid gap-3 md:grid-cols-3" key={index}><Field label="Payment method"><select className={inputStyle} value={p.method} disabled={busy} onChange={e=>{key.current="";setParts(parts.map((x,i)=>i===index?{...x,method:e.target.value}:x))}}>{["CASH","MOBILE_MONEY","CARD","BANK_TRANSFER"].map(m=><option key={m} value={m}>{t(m)}</option>)}</select></Field><Field label="Amount"><input type="number" min="0.0001" step="0.0001" className={inputStyle} value={p.amount} disabled={busy} onChange={e=>{key.current="";setParts(parts.map((x,i)=>i===index?{...x,amount:Number(e.target.value)}:x))}}/></Field><button disabled={busy||parts.length===1} onClick={()=>{key.current="";setParts(parts.filter((_,i)=>i!==index))}}>{t("Remove")}</button></div>)}<button className={buttonStyle} disabled={busy||parts.length>=8} onClick={()=>{key.current="";setParts([...parts,{method:"CASH",amount:0}])}}>{t("Add payment method")}</button><p>{t("Payment total")}: {total.toFixed(2)} {folio.currency}</p><p>{t("Remaining after approval")}: {(Number(folio.balance)-total).toFixed(2)} {folio.currency}</p><button className={buttonStyle} disabled={busy||total<=0||total>Number(folio.balance)||parts.some(p=>p.amount<=0)} onClick={submit}>{t("Confirm payment for approval")}</button>{message&&<p role="status">{t(message)}</p>}</div>}
 </>}</Panel>}

