"use client";
import {useEffect,useRef,useState} from "react";
import {useSession} from "next-auth/react";
import {ProductEditor} from "@/components/operations/ProductEditor";
import {MasterData,Row} from "@/components/operations/MasterData";
import {productFields} from "@/components/operations/fields";
import {api,all} from "@/lib/hms-api";
import {Panel,Field,inputStyle,buttonStyle} from "@/components/operations/ui";
import {useLocale} from "@/components/LocaleProvider";
function StockDetail({product}:{product:Row}){const {t}=useLocale();const {data:session}=useSession();const canAdjust=(session?.user as {permissions?:string[]})?.permissions?.includes("INVENTORY_ADJUST");const [stock,setStock]=useState<{quantity:number;unit:string}|null>(null);const [history,setHistory]=useState<Row[]>([]);const [quantity,setQuantity]=useState(0);const [kind,setKind]=useState("OPENING");const [reason,setReason]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const key=useRef("");async function load(){setStock(await api(`inventory/${product.id}`));setHistory(await all<Row>(`inventory/${product.id}/movements`))}useEffect(()=>{load().catch(e=>setError(e.message))},[product.id]);async function adjust(){setBusy(true);setError("");try{key.current||=crypto.randomUUID();await api("inventory/adjustments","POST",{productId:product.id,quantity,kind,reason,requestId:key.current});key.current="";setQuantity(0);setReason("");await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}return <Panel title="Stock movements" error={error}><div className="rounded-xl border bg-white p-5 space-y-4"><h2 className="text-xl">{String(product.name)} · {stock?.quantity} {stock?.unit}</h2>{canAdjust&&<><div className="grid gap-3 md:grid-cols-3"><Field label="Movement type"><select className={inputStyle} value={kind} onChange={e=>{key.current="";setKind(e.target.value)}}>{["OPENING","ADJUSTMENT","WASTE"].map(k=><option key={k} value={k}>{t(k)}</option>)}</select></Field><Field label="Quantity"><input type="number" step="0.0001" className={inputStyle} value={quantity} onChange={e=>{key.current="";setQuantity(Number(e.target.value))}}/></Field><Field label="Reason"><input className={inputStyle} value={reason} onChange={e=>{key.current="";setReason(e.target.value)}}/></Field></div><button className={buttonStyle} disabled={busy||quantity===0||!reason.trim()} onClick={adjust}>{t("Confirm stock movement")}</button></>}<table className="w-full text-left text-sm"><thead><tr>{["Type","Quantity","Reason"].map(k=><th key={k}>{t(k)}</th>)}</tr></thead><tbody>{history.map(r=><tr key={r.id} className="border-t"><td className="py-2">{t(String(r.kind))}</td><td>{String(r.quantity)}</td><td>{String(r.reason)}</td></tr>)}</tbody></table></div></Panel>}
export default function Stock(){return <MasterData title="Products and stock" resource="products" fields={productFields} columns={["sku","name","category","sellingPrice","purchasePrice","stockTracked","active"]} extra={(row,refresh)=><div key={row.id} className="space-y-5"><ProductEditor product={row} onSaved={refresh}/><StockDetail product={row}/></div>}/>}


