"use client";
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {api,all} from "@/lib/hms-api";
import {Panel,Field,inputStyle,buttonStyle} from "@/components/operations/ui";
import {useLocale} from "@/components/LocaleProvider";
type Room={id:string;code:string;active:boolean;operational:string;bedDimensions:string};type Reservation={id:string;reference:string;customerId:string;checkIn:string;checkOut:string;status:string;roomIds:string[];adults:number;children:number;folioId:string};
const shift=(day:string,n:number)=>new Date(new Date(`${day}T00:00:00Z`).getTime()+n*86400000).toISOString().slice(0,10);
export default function Reservations(){const {t}=useLocale();const [rooms,setRooms]=useState<Room[]>([]);const [rows,setRows]=useState<Reservation[]>([]);const [names,setNames]=useState<Record<string,string>>({});const [start,setStart]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const load=useCallback(()=>all<Reservation>("reservations").then(setRows),[]);useEffect(()=>{setStart(new Date().toISOString().slice(0,10));Promise.all([load(),all<Room>("rooms").then(setRooms),all<{id:string;name:string}>("customers").then(c=>setNames(Object.fromEntries(c.map(x=>[x.id,x.name]))))]).catch(e=>setError(e.message))},[load]);const days=start?Array.from({length:14},(_,i)=>shift(start,i)):[];
 async function cancel(id:string){setBusy(true);setError("");try{await api(`reservations/${id}/cancel`,"POST");await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Panel title="Reservations" error={error}><div className="flex items-end justify-between gap-5"><Field label="Calendar start"><input type="date" className={inputStyle} value={start} onChange={e=>setStart(e.target.value)}/></Field><Link href="/reservations/new" className={buttonStyle}>{t("New reservation")}</Link></div><p>{t("Select an available day to start a reservation")}</p><div className="overflow-auto rounded-xl border bg-white"><table className="w-full text-center text-sm"><thead><tr><th className="p-3">{t("Room")}</th>{days.map(d=><th key={d} className="p-2 whitespace-nowrap">{d.slice(5)}</th>)}</tr></thead><tbody>{rooms.map(room=><tr key={room.id} className="border-t"><th className="p-3 whitespace-nowrap">{room.code}<small className="block font-normal">{room.bedDimensions}</small></th>{days.map(day=>{const reservation=rows.find(r=>!["CANCELLED","CHECKED_OUT"].includes(r.status)&&r.roomIds.includes(room.id)&&r.checkIn<=day&&r.checkOut>day);const available=room.active&&room.operational==="AVAILABLE"&&!reservation;return <td key={day} className={`border p-2 ${available?"bg-emerald-50 text-emerald-800":"bg-rose-50 text-rose-800"}`}>{available?<Link href={`/reservations/new?checkIn=${day}&checkOut=${shift(day,1)}`} aria-label={`${t("Room")} ${room.code} ${day} ${t("Available")}`}>{t("Available")}</Link>:<span title={reservation?`${names[reservation.customerId]??""} ${reservation.reference}`:t(room.operational)}>{t(reservation?"Reserved":"Unavailable")}</span>}</td>})}</tr>)}</tbody></table></div><div className="rounded-xl border bg-white overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{["Reference","Customer","Dates","Adults","Children","Status","Actions"].map(s=><th key={s} className="p-3">{t(s)}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-3">{r.reference}</td><td>{names[r.customerId]}</td><td>{r.checkIn} → {r.checkOut}</td><td>{r.adults}</td><td>{r.children}</td><td>{t(r.status)}</td><td>{r.status==="CONFIRMED"&&<button disabled={busy} className="text-red-700" onClick={()=>cancel(r.id)}>{t("Cancel reservation")}</button>}</td></tr>)}</tbody></table></div></Panel>
}
